### ISSUE TITLE
Not able to update

### ISSUE THREAD

**Issue by PolGuixe** [Zetoff/accounts-material-ui#13]
From @philcruz:
I tried updating and I get

The following top-level dependencies were not updated to the very latest version available:

zetoff:accounts-material-ui 0.0.4 (0.0.7 is available)
I removed the package and added it back but it only adds 0.0.4. What am I missing?

**Comment by PolGuixe** [comment]
@philcruz: do you have a repo where I can try it?

**Comment by philcruz** [comment]
@PolGuixe No, I don't but I figured it out. Trying to specific 0.0.8 I got this error:

```

➜  server-console git:(update-packages) ✗ meteor add zetoff:accounts-material-ui@0.0.8
 => Errors while adding packages:

While selecting package versions:
error: Conflict: Constraint std:accounts-ui@1.2.9 is not satisfied by std:accounts-ui 1.2.8.
Constraints on package "std:accounts-ui":
* std:accounts-ui@=1.2.8 <- top level
* std:accounts-ui@1.2.9 <- zetoff:accounts-material-ui 0.0.8
```

I'm using a local version of std:accounts-ui in my /packages directory because I applied a PR that hasn't been merged in the published version. That local package was a an old version. I updated my local package and that resolved the issue.

**Comment by PolGuixe** [comment]
Ok cool! 

I'll close the issue then.
