### ISSUE TITLE
material-ui@0.15.4 needed?

### ISSUE THREAD

**Issue by philcruz** [Zetoff/accounts-material-ui#7]
Getting this warning:
"tmeasday_check-npm-versions.js?hash=ade7cba…:89 WARNING: npm peer requirements (for zetoff:accounts-material-ui) not installed:
 - material-ui@0.16.1 installed, material-ui@0.15.4 needed"

Is 0.15.4 still needed?

**Comment by mostlyharmless2024** [comment]
In your main meteor install:
`.meteor\packages\zetoff_accounts-material-ui\0.0.4\web.browser`

You can edit the "check_npm.js" file, change line 3 to:

`'material-ui': '0.16.1'`

FYI this isn't really recommended but for the sake of testing- a quick look at the "main.jsx" (in that same folder) it does look like the following:

`import {RaisedButton, FlatButton, FontIcon, TextField, Divider} from 'material-ui';`

Should be compatible with MUI 0.16.1 - @PolGuixe could you confirm this and if you're confident update the meteor package?

Regardless- great work!

edit- not sure if this is a 0.16.1 incompatibility or something i'm doing wrong but:

`modules.js?hash=3d61712…:21993 Uncaught Error: Objects are not valid as a React child (found: object with keys {message, type}). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons.(…)`

When i click submit on the Register form.

edit x2 - Looks like wiping node_modules made things work.

I get a warning in the console instead of a error:
`check-npm-versions.js:53 WARNING: npm peer requirements (for zetoff:accounts-material-ui) not installed:
- material-ui@0.16.2 installed, material-ui@0.15.4 needed
  `

So that's a plus, and the react error is gone too.

**Comment by PolGuixe** [comment]
@brendonlamb thanks for all the info! I'll try to fix it today. ;)

**Comment by PolGuixe** [comment]
@brendonlamb let me know if you have any issues with v.0.0.6

**Comment by PolGuixe** [comment]
@brendonlamb I don't understand: 

> FYI this isn't really recommended but for the sake of testing- a quick look at the "main.jsx" (in that same folder) it does look like the following:
> import {RaisedButton, FlatButton, FontIcon, TextField, Divider} from 'material-ui';

**Comment by mostlyharmless2024** [comment]
@PolGuixe i was just noting that those MUI components:
`import {RaisedButton, FlatButton, FontIcon, TextField, Divider} from 'material-ui';`

Are valid within MUI 0.16.2 (as far as i could tell)

Trying v.0.0.6 now!

**Comment by PolGuixe** [comment]
@brendonlamb would probably give you problems. I am just working on v0.0.7
Give 5 min. :)

**Comment by mostlyharmless2024** [comment]
Yep I'm seeing it :D  - no worries!

![image](https://cloud.githubusercontent.com/assets/1816511/20314848/acf5e056-ab29-11e6-8306-e6d3ce3c8112.png)

**Comment by PolGuixe** [comment]
published. Try if v0.0.7 works for you.

**Comment by mostlyharmless2024** [comment]
Hmm- seemed like it was working fine at first but it seems like theres some larger issues. I can't register or change password. Just get piles of

`Uncaught Error: Objects are not valid as a React child (found: object with keys {message, type}). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons.(…)`

(client-side of course) 

Just confirming, i'm using:

```
    "babel-plugin-transform-class-properties": "^6.10.2",
    "material-ui": "^0.16.2",
    "meteor-node-stubs": "~0.2.0",
    "react": "^15.3.2",
    "react-addons-pure-render-mixin": "^15.3.2",
    "react-dom": "^15.3.2",
    "react-mounter": "^1.2.0",
    "react-tap-event-plugin": "^1.0.0"
```

My meteor packages looks like:

```
react-meteor-data
accounts-password
zetoff:accounts-material-ui
```

I've been able to make a super-basic login component myself w/ the above packages, but it's no where near as feature complete as yours appears.

**Comment by philcruz** [comment]
I was getting similar errors. I mentioned in #8. For me, it turns out there were issues in std:accounts-ui. I applied this PR (https://github.com/studiointeract/accounts-ui/pull/75) to a local version of the package and it fixed it.

**Comment by PolGuixe** [comment]
When do you get this error? At which event of form?

**Comment by mostlyharmless2024** [comment]
It looks like the same issue as #8  @philcruz  mentioned.

That said- the std:accounts-ui PR that was mentioned didn't fix it for me.

Really not sure what's going on :/

**Comment by PolGuixe** [comment]
@brendonlamb what event causes the error? or is it right away?

**Comment by mostlyharmless2024** [comment]
Steps:

Login, Log out. Now try logging back in.

![image](https://cloud.githubusercontent.com/assets/1816511/20318472/5ddcd556-ab38-11e6-8d7e-8d140ae26d69.png)

Once i get this error i can't do anything, logging in/out, register, everything breaks until a full page reload.

**Comment by philcruz** [comment]
I tried updating and I get

The following top-level dependencies were not updated to the very latest version available:
- zetoff:accounts-material-ui 0.0.4 (0.0.7 is available)

I removed the package and added it back but it only adds 0.0.4. What am I missing?

**Comment by PolGuixe** [comment]
For better tracking. Can we create two different issues? 

:)

**Comment by PolGuixe** [comment]
@philcruz I moved your issue here: https://github.com/Zetoff/accounts-material-ui/issues/13

**Comment by PolGuixe** [comment]
@brendonlamb  I moved your issue here: https://github.com/Zetoff/accounts-material-ui/issues/14

**Comment by PolGuixe** [comment]
I think this one can be closed now.
